FROM FROM_IMAGE

RUN yum erase -y vim-minimal && \
	groupadd -g 990 docker && \
	yum groupinstall -y "development tools" && \
	yum install -y --setopt=override_install_langs=en --setopt=tsflags=nodocs \
	yum-utils \
	git \
	golang \
	mercurial \
	bzr \
	vim-enhanced \
	quilt \
	fedora-packager \
	sudo \
	screen \
	libtool \
	gtk-doc \
	intltool \
	libgcrypt-devel \
	gperf \
	libcap-devel \
	wget \
	tig \
	glibc-static \
	device-mapper-devel \
	btrfs-progs-devel \
	sqlite-devel \
	glib2-devel \
	libmount-devel \
	dbus-devel \
	keychain \
	tito && \
	yum update -y && \
	yum clean all && \
	groupadd -g DEV_GID DEV_USER && \
	useradd -m -u DEV_UID -g DEV_GID -G wheel,mock DEV_USER && \
	sed -ri 's/^(%wheel.*)(ALL)$/\1NOPASSWD: \2/' /etc/sudoers
USER DEV_USER
ENV HOME /home/DEV_USER
WORKDIR /home/DEV_USER
CMD bash -l
