FROM fedora:rawhide

RUN yum erase -y vim-minimal &&\
	yum groupinstall -y "development tools" && \
	yum install -y --setopt=override_install_langs=en --setopt=tsflags=nodocs \
	yum-utils \
	git \
	golang \
	mercurial \
	bzr \
	vim-enhanced \
	fedora-packager \
	sudo \
	screen \
	libtool \
	gtk-doc \
	intltool \
	libgcrypt-devel \
	gperf \
	libcap-devel \
	glib2-devel \
	keychain \
	tito && \
	yum update -y && \
	yum clean all && \
	useradd -m -u 1000 -G wheel,mock vbatts && \
	sed -ri 's/^(%wheel.*)(ALL)$/\1NOPASSWD: \2/' /etc/sudoers
USER vbatts
ENV HOME /home/vbatts
WORKDIR /home/vbatts
CMD bash -l
